azs:
- name: z1
  cloud_properties: {}
- name: z2
  cloud_properties: {}

vm_types:
- name: small
  cloud_properties: {}

disk_types:
- name: small
  disk_size: 10240
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.238.0/24
    gateway: 10.244.238.1
    az: z1
    cloud_properties: {}

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: small
  network: default
