azs:
- name: z1

vm_types:
- name: small
  cloud_properties:
    instance_type: m1.small

disk_types:
- name: small
  disk_size: 5000
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.10.4.0/24
    gateway: 10.10.4.1
    reserved:
    - 10.10.4.1 - 10.10.4.5
    az: z1
    cloud_properties:
      net_id: 936559dd-88ff-4382-9c0c-e64a24cc9db8

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: small
  network: default