azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: small
  cloud_properties:
    instance_type: Standard_A1_v2
- name: medium
  cloud_properties:
    instance_type: Standard_A2_v2
- name: large
  cloud_properties:
    instance_type: Standard_A4_v2
- name: xlarge
  cloud_properties:
    instance_type: Standard_D4s_v3

disk_types:
- name: default
  disk_size: 3000
- name: small
  disk_size: 5000
- name: medium
  disk_size: 10000
- name: large
  disk_size: 50_000
- name: xlarge
  disk_size: 100_000

networks:
- name: default-m
  type: manual
  subnets:
  - range: 10.244.1.0/24
    gateway: 10.244.1.1
    azs: [z1, z2, z3]
    dns: [168.63.129.16]
    reserved: 10.244.1.2-10.244.1.80
#    static: ((static_ips))
    cloud_properties:
      virtual_network_name: cloud-service
      subnet_name: cf2
      security_group: cloud-service

- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: default-m
