---
name: msxpert

releases:
- name: msxpert
  version: latest
- name: postgres
  version: 23

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: studio
  instances: 1
  vm_type: default
  vm_extensions: []
  stemcell: trusty
  azs: [z1]
  networks:
  - default:
    - gateway
    - dns
    name: default
  - name: vip
    static_ips:
    - 52.141.44.167
  jobs:
  - name: studio
    release: msxpert
    properties:
      bind_ip: 0.0.0.0
      bind_port: 8080
      #tls:
      #  certificate: 
      #  private_key:
      postgresql:
        database: &db_name microservice
        role: &db_role
          name: microservice
          password: dummy-postgres-password
      cf:
        api_url: *cf_api
        uaa_url : https://uaa.cloudxpert.co.kr
        username: *cf_username
        password: *cf_password
        skip_cert_check: *cf_cert_check
        client_id: micro
        client_secret: micro-secret
  - name: microservice-broker
    release: msxpert
    properties:
      broker:
        username: admin
        password: admin
        port: 3000
      cf:
        api: &cf_api https://api.cloudxpert.co.kr
        username: &cf_username admin
        password: &cf_password admin
        organization: org-micro
        space: space-micro
        skip_cert_check: &cf_cert_check true

- name: db
  instances: 1
  vm_type: default
  stemcell: trusty
  persistent_disk_type: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role

#- name: vault
#  instances: 1
#  vm_type: small
#  vm_extensions: []
#  stemcell: trusty
#  azs: [z1]
#  networks: [{name: default-m}]
#  jobs:
#  - name: vault
#    release: msxpert
#    properties:
#      bind_ip: 0.0.0.0
#      bind_port: 8200
      #tls:
      #  certificate:
      #  private_key:

- name: broker-registrar-micro
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: broker-registrar
    release: msxpert
    properties:
      servicebroker:
        url: http://10.244.228.2:3000 #https://my-broker.system.domain
        name: microservicebroker
        username: admin
        password: admin
      cf:
        api_url: *cf_api
        username: *cf_username
        password: *cf_password
        skip_ssl_validation: *cf_cert_check

- name: broker-deregistrar-micro
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: broker-deregistrar
    release: msxpert
    properties:
      servicebroker:
        name: microservicebroker
      cf:
        api_url: *cf_api
        username: *cf_username
        password: *cf_password
        skip_ssl_validation: *cf_cert_check

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
