# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: <%= p('grafana.prometheus.datasource_name') %>
    orgId: 1

<% if_link('http_prometheus') do |prometheus| %>
<%
  # Try to pick the prometheus instance deployed at the same az
  pinstances = prometheus.instances.select { |instance| instance.az == spec.az }
  prometheus_ip = pinstances.empty? ? prometheus.instances.first.address : pinstances.first.address

  purl = "http://#{prometheus_ip}:#{prometheus.p('prometheus.web.port')}"
  pbasic_auth = "false"
  pbasic_auth_user = ""
  pbasic_auth_password = ""
  pjson_data = ""

%>

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: <%= p('grafana.prometheus.datasource_name') %>
    # <int> datasource config version
    version: 1
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <string> url
    url: <%= purl %>
    # <bool> enable/disable basic auth
    basicAuth: <%= pbasic_auth %>
    # <string> basic auth username
    basicAuthUser: <%= pbasic_auth_user %>
    # <string> basic auth password
    basicAuthPassword: <%= pbasic_auth_password %>
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <map> fields that will be converted to json and stored in json_data
    jsonData: <%= pjson_data %>
    # <bool> allow users to edit datasources from the UI.
    editable: false
<% end %>